In [27]:
import pandas as pd

In [28]:
files = [
    "Cherkasy.csv", "Chernihiv.csv", "Chernivtsi.csv", "Dnipro.csv", "Ivano-Frankivsk.csv",
    "Kharkiv.csv", "Kherson.csv", "Khmelnytskyi.csv", "Kropyvnytskyi.csv",
    "Lutsk.csv", "Lviv.csv", "Mykolaiv.csv", "Odesa.csv", "Poltava.csv", "Rivne.csv",
    "Sumy.csv", "Ternopil.csv", "Uzhhorod.csv", "Vinnytsia.csv", "Zaporizhzhia.csv",
    "Zhytomyr.csv"
]

dfs = []
for filename in files:
    df = pd.read_csv(filename)
    dfs.append(df)
    print(f"✓ {filename}")

df_ukraine = pd.concat(dfs, ignore_index=True)

✓ Cherkasy.csv
✓ Chernihiv.csv
✓ Chernivtsi.csv
✓ Dnipro.csv
✓ Ivano-Frankivsk.csv
✓ Kharkiv.csv
✓ Kherson.csv
✓ Khmelnytskyi.csv
✓ Kropyvnytskyi.csv
✓ Lutsk.csv
✓ Lviv.csv
✓ Mykolaiv.csv
✓ Odesa.csv
✓ Poltava.csv
✓ Rivne.csv
✓ Sumy.csv
✓ Ternopil.csv
✓ Uzhhorod.csv
✓ Vinnytsia.csv
✓ Zaporizhzhia.csv
✓ Zhytomyr.csv

In [29]:
df_ukraine.info()

<class 'pandas.DataFrame'>
RangeIndex: 41477 entries, 0 to 41476
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   num_of_rooms       41477 non-null  int64
 1   freshly_renovated  41041 non-null  object
 2   area               41477 non-null  float64
 3   living_area        41477 non-null  float64
 4   kitchen_area       41477 non-null  float64
 5   floor              41477 non-null  float64
 6   floors_in_house    41477 non-null  float64
 7   year_of_building   41477 non-null  int64
 8   price              40879 non-null  float64
 9   url                41477 non-null  str
 10  district           41477 non-null  str
 11  city               41477 non-null  str
 12  geo_region         41477 non-null  str
dtypes: float64(6), int64(2), object(1), str(4)
memory usage: 4.1+ MB

In [30]:
large_cities = ['Lviv', 'Odesa', 'Dnipro', 'Kharkiv']
df_ukraine['is_large_city'] = df_ukraine['city'].isin(large_cities).astype(int)

border_eu_cities = ['Lviv', 'Uzhhorod', 'Ivano-Frankivsk', 'Lutsk', 'Chernivtsi', 'Ternopil', 'Rivne']
df_ukraine['is_close_to_eu'] = df_ukraine['city'].isin(border_eu_cities).astype(int)

border_risk_cities = ['Sumy', 'Chernihiv', 'Kharkiv', 'Zhytomyr', 'Lutsk', 'Rivne']
df_ukraine['is_near_border_threat'] = df_ukraine['city'].isin(border_risk_cities).astype(int)

tourist_cities = ['Lviv', 'Odesa', 'Ivano-Frankivsk', 'Uzhhorod', 'Chernivtsi']
df_ukraine['is_tourist_hub'] = df_ukraine['city'].isin(tourist_cities).astype(int)

df_ukraine['is_low_floor'] = 0
df_ukraine['is_high_floor'] = 0

high_mask = df_ukraine['floors_in_house'] > 6
df_ukraine.loc[high_mask & (df_ukraine['floor'] <= 3), 'is_low_floor'] = 1
df_ukraine.loc[high_mask & (df_ukraine['floor'] > (df_ukraine['floors_in_house'] - 3)), 'is_high_floor'] = 1

low_mask = df_ukraine['floors_in_house'] <= 6
df_ukraine.loc[low_mask & (df_ukraine['floor'] == 1), 'is_low_floor'] = 1
df_ukraine.loc[low_mask & (df_ukraine['floor'] == df_ukraine['floors_in_house']), 'is_high_floor'] = 1

df_ukraine['is_historic_or_stalinka'] = (df_ukraine['year_of_building'] < 1956).astype(int)
df_ukraine['is_khrushchev'] = ((df_ukraine['floors_in_house'] <= 5) & (df_ukraine['year_of_building'] >= 1956) & (df_ukraine['year_of_building'] <= 1980)).astype(int)
df_ukraine['is_soviet_panel'] = ((df_ukraine['floors_in_house'] > 5) & (df_ukraine['floors_in_house'] <= 16) & (df_ukraine['year_of_building'] >= 1970) & (df_ukraine['year_of_building'] <= 1995)).astype(int)
df_ukraine['is_modern_fund'] = ((df_ukraine['year_of_building'] >= 2010) | (df_ukraine['floors_in_house'] > 16)).astype(int)

In [31]:
df_Kyiv = pd.read_csv("Kyiv.csv")

In [32]:
df_ukraine.drop_duplicates(ignore_index=True, inplace=True)
df_Kyiv.drop_duplicates(ignore_index=True, inplace=True)

In [33]:
cols_2 = ["area", "living_area", "kitchen_area"]
cols_0 = ["floor", "floors_in_house"]

df_ukraine[cols_2] = df_ukraine[cols_2].round(2)
df_ukraine[cols_0] = df_ukraine[cols_0].round().astype(int)

df_Kyiv[cols_2] = df_Kyiv[cols_2].round(2)
df_Kyiv[cols_0] = df_Kyiv[cols_0].round().astype(int)

In [34]:
df_ukraine.info()

<class 'pandas.DataFrame'>
RangeIndex: 37182 entries, 0 to 37181
Data columns (total 23 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   num_of_rooms             37182 non-null  int64
 1   freshly_renovated        36782 non-null  object
 2   area                     37182 non-null  float64
 3   living_area              37182 non-null  float64
 4   kitchen_area             37182 non-null  float64
 5   floor                    37182 non-null  int64
 6   floors_in_house          37182 non-null  int64
 7   year_of_building         37182 non-null  int64
 8   price                    36606 non-null  float64
 9   url                      37182 non-null  str
 10  district                 37182 non-null  str
 11  city                     37182 non-null  str
 12  geo_region               37182 non-null  str
 13  is_large_city            37182 non-null  int64
 14  is_close_to_eu           37182 non-null  int64
 15  is_near_border_threat    37182 non-null  int64
 16  is_tourist_hub           37182 non-null  int64
 17  is_low_floor             37182 non-null  int64
 18  is_high_floor            37182 non-null  int64
 19  is_historic_or_stalinka  37182 non-null  int64
 20  is_khrushchev            37182 non-null  int64
 21  is_soviet_panel          37182 non-null  int64
 22  is_modern_fund           37182 non-null  int64
dtypes: float64(4), int64(14), object(1), str(4)
memory usage: 6.5+ MB

In [35]:
df_ukraine.drop(["url"], axis=1, inplace=True)
df_Kyiv.drop(["url"], axis=1, inplace=True)

In [36]:
df_ukraine = df_ukraine[df_ukraine["price"].notnull()]
df_Kyiv = df_Kyiv[df_Kyiv["price"].notnull()]

In [37]:
df_ukraine.info()

<class 'pandas.DataFrame'>
Index: 36606 entries, 0 to 37180
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   num_of_rooms             36606 non-null  int64
 1   freshly_renovated        36221 non-null  object
 2   area                     36606 non-null  float64
 3   living_area              36606 non-null  float64
 4   kitchen_area             36606 non-null  float64
 5   floor                    36606 non-null  int64
 6   floors_in_house          36606 non-null  int64
 7   year_of_building         36606 non-null  int64
 8   price                    36606 non-null  float64
 9   district                 36606 non-null  str
 10  city                     36606 non-null  str
 11  geo_region               36606 non-null  str
 12  is_large_city            36606 non-null  int64
 13  is_close_to_eu           36606 non-null  int64
 14  is_near_border_threat    36606 non-null  int64
 15  is_tourist_hub           36606 non-null  int64
 16  is_low_floor             36606 non-null  int64
 17  is_high_floor            36606 non-null  int64
 18  is_historic_or_stalinka  36606 non-null  int64
 19  is_khrushchev            36606 non-null  int64
 20  is_soviet_panel          36606 non-null  int64
 21  is_modern_fund           36606 non-null  int64
dtypes: float64(4), int64(14), object(1), str(3)
memory usage: 6.4+ MB

In [38]:
df_Kyiv.info()

<class 'pandas.DataFrame'>
Index: 14144 entries, 0 to 14488
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   num_of_rooms       14144 non-null  int64
 1   freshly_renovated  13856 non-null  object
 2   area               14144 non-null  float64
 3   living_area        14144 non-null  float64
 4   kitchen_area       14144 non-null  float64
 5   floor              14144 non-null  int64
 6   floors_in_house    14144 non-null  int64
 7   year_of_building   14144 non-null  int64
 8   price              14144 non-null  float64
 9   district           14144 non-null  str
 10  city               14144 non-null  str
 11  geo_region         14144 non-null  str
dtypes: float64(4), int64(4), object(1), str(3)
memory usage: 1.4+ MB

In [39]:
df_ukraine = df_ukraine[df_ukraine["freshly_renovated"].notnull()]
df_Kyiv = df_Kyiv[df_Kyiv["freshly_renovated"].notnull()]

In [40]:
cols_to_clean = ["price", "area"]

def remove_outliers_iqr(group):
    clean_group = group.copy()
    
    for col in cols_to_clean:
        Q1 = clean_group[col].quantile(0.25)
        Q3 = clean_group[col].quantile(0.75)
        IQR = Q3 - Q1
        
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR

        clean_group = clean_group[(clean_group[col] >= lower_bound) & (clean_group[col] <= upper_bound)]
        
    return clean_group

df_ukraine_clean = remove_outliers_iqr(df_ukraine)
df_Kyiv_clean = remove_outliers_iqr(df_Kyiv)

In [41]:
df_ukraine_clean.describe()

,num_of_rooms,area,living_area,kitchen_area,floor,floors_in_house,year_of_building,price,is_large_city,is_close_to_eu,is_near_border_threat,is_tourist_hub,is_low_floor,is_high_floor,is_historic_or_stalinka,is_khrushchev,is_soviet_panel,is_modern_fund
count,32898.000000,32898.000000,32898.000000,32898.000000,32898.000000,32898.000000,32898.000000,32898.000000,32898.000000,32898.000000,32898.000000,32898.000000,32898.000000,32898.000000,32898.000000,32898.000000,32898.000000,32898.000000
mean,1.899629,56.213662,31.215530,12.526951,6.540793,10.856982,2000.626725,1073.837680,0.688188,0.160040,0.164508,0.504803,0.210256,0.335613,0.058332,0.107393,0.139461,0.553620
std,0.852187,20.555029,13.929102,7.066351,5.128663,6.787568,27.103942,476.160139,0.463241,0.366649,0.370742,0.499985,0.407497,0.472212,0.234373,0.309616,0.346433,0.497124
min,1.000000,8.600000,1.000000,1.000000,1.000000,1.000000,1507.000000,24.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,42.000000,18.930000,7.700000,3.000000,5.000000,1984.000000,727.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2.000000,52.000000,29.910000,10.500000,5.000000,9.000000,2013.000000,982.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,3.000000,68.500000,40.000000,15.247500,9.000000,14.000000,2021.000000,1350.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
max,6.000000,117.000000,132.560000,110.000000,30.000000,127.000000,2028.000000,2447.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [42]:
df_ukraine_clean = df_ukraine_clean[df_ukraine_clean['kitchen_area'] < df_ukraine_clean['area']]
df_ukraine_clean = df_ukraine_clean[df_ukraine_clean['living_area'] < df_ukraine_clean['area']]
df_ukraine_clean = df_ukraine_clean[(df_ukraine_clean['living_area'] + df_ukraine_clean['kitchen_area']) <= df_ukraine_clean['area']]

df_ukraine_clean = df_ukraine_clean[df_ukraine_clean['floors_in_house'] <= 50]
df_ukraine_clean = df_ukraine_clean[df_ukraine_clean['floor'] <= df_ukraine_clean['floors_in_house']]

df_ukraine_clean = df_ukraine_clean[df_ukraine_clean['area'] >= 15]
df_ukraine_clean = df_ukraine_clean[df_ukraine_clean['living_area'] >= 9]
df_ukraine_clean = df_ukraine_clean[df_ukraine_clean['kitchen_area'] >= 4]
df_ukraine_clean = df_ukraine_clean[df_ukraine_clean['price'] >= 200]

df_ukraine_clean.describe()

,num_of_rooms,area,living_area,kitchen_area,floor,floors_in_house,year_of_building,price,is_large_city,is_close_to_eu,is_near_border_threat,is_tourist_hub,is_low_floor,is_high_floor,is_historic_or_stalinka,is_khrushchev,is_soviet_panel,is_modern_fund
count,30399.000000,30399.000000,30399.000000,30399.000000,30399.000000,30399.000000,30399.000000,30399.000000,30399.000000,30399.000000,30399.000000,30399.000000,30399.000000,30399.000000,30399.000000,30399.000000,30399.000000,30399.000000
mean,1.918714,57.358158,31.107313,12.389722,6.575578,10.869535,2000.489029,1073.859074,0.678838,0.167670,0.162999,0.507813,0.207507,0.336952,0.056745,0.108754,0.147011,0.547650
std,0.850572,20.044693,13.406326,6.482527,5.089398,6.615811,26.989320,474.493590,0.466931,0.373579,0.369371,0.499947,0.405528,0.472676,0.231359,0.311335,0.354123,0.497733
min,1.000000,15.000000,9.000000,4.000000,1.000000,1.000000,1507.000000,200.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,42.600000,19.000000,8.000000,3.000000,5.000000,1984.000000,727.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2.000000,53.100000,30.000000,10.400000,5.000000,9.000000,2012.000000,980.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,3.000000,69.000000,40.000000,15.000000,9.000000,14.000000,2021.000000,1349.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
max,6.000000,117.000000,100.000000,75.000000,29.000000,50.000000,2028.000000,2447.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [43]:
df_ukraine_clean.info()

<class 'pandas.DataFrame'>
Index: 30399 entries, 0 to 37180
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   num_of_rooms             30399 non-null  int64
 1   freshly_renovated        30399 non-null  object
 2   area                     30399 non-null  float64
 3   living_area              30399 non-null  float64
 4   kitchen_area             30399 non-null  float64
 5   floor                    30399 non-null  int64
 6   floors_in_house          30399 non-null  int64
 7   year_of_building         30399 non-null  int64
 8   price                    30399 non-null  float64
 9   district                 30399 non-null  str
 10  city                     30399 non-null  str
 11  geo_region               30399 non-null  str
 12  is_large_city            30399 non-null  int64
 13  is_close_to_eu           30399 non-null  int64
 14  is_near_border_threat    30399 non-null  int64
 15  is_tourist_hub           30399 non-null  int64
 16  is_low_floor             30399 non-null  int64
 17  is_high_floor            30399 non-null  int64
 18  is_historic_or_stalinka  30399 non-null  int64
 19  is_khrushchev            30399 non-null  int64
 20  is_soviet_panel          30399 non-null  int64
 21  is_modern_fund           30399 non-null  int64
dtypes: float64(4), int64(14), object(1), str(3)
memory usage: 5.3+ MB

In [44]:
df_Kyiv_clean = df_Kyiv_clean[df_Kyiv_clean['kitchen_area'] < df_Kyiv_clean['area']]
df_Kyiv_clean = df_Kyiv_clean[df_Kyiv_clean['living_area'] < df_Kyiv_clean['area']]
df_Kyiv_clean = df_Kyiv_clean[(df_Kyiv_clean['living_area'] + df_Kyiv_clean['kitchen_area']) <= df_Kyiv_clean['area']]

df_Kyiv_clean = df_Kyiv_clean[df_Kyiv_clean['floors_in_house'] <= 50]
df_Kyiv_clean = df_Kyiv_clean[df_Kyiv_clean['floor'] <= df_Kyiv_clean['floors_in_house']]

df_Kyiv_clean = df_Kyiv_clean[df_Kyiv_clean['area'] >= 15]
df_Kyiv_clean = df_Kyiv_clean[df_Kyiv_clean['living_area'] >= 9]
df_Kyiv_clean = df_Kyiv_clean[df_Kyiv_clean['kitchen_area'] >= 4]
df_Kyiv_clean = df_Kyiv_clean[df_Kyiv_clean['price'] >= 200]

df_Kyiv_clean.describe()

,num_of_rooms,area,living_area,kitchen_area,floor,floors_in_house,year_of_building,price
count,12026.000000,12026.000000,12026.000000,12026.000000,12026.000000,12026.000000,12026.000000,12026.000000
mean,2.068934,69.064376,35.118131,15.130107,10.224514,17.713537,2002.547148,1843.061367
std,0.926570,28.972150,17.794079,8.155247,7.043753,8.369592,25.299881,745.626697
min,1.000000,16.300000,9.000000,4.000000,1.000000,1.000000,1858.000000,256.000000
25%,1.000000,45.900000,19.000000,9.000000,4.000000,9.000000,1987.000000,1288.000000
50%,2.000000,64.000000,32.000000,14.000000,9.000000,19.000000,2014.000000,1655.000000
75%,3.000000,85.600000,45.000000,19.000000,15.000000,25.000000,2021.000000,2263.000000
max,6.000000,158.000000,125.000000,67.000000,36.000000,46.000000,2028.000000,4208.000000

In [45]:
df_Kyiv_clean.info()

<class 'pandas.DataFrame'>
Index: 12026 entries, 0 to 14488
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   num_of_rooms       12026 non-null  int64
 1   freshly_renovated  12026 non-null  object
 2   area               12026 non-null  float64
 3   living_area        12026 non-null  float64
 4   kitchen_area       12026 non-null  float64
 5   floor              12026 non-null  int64
 6   floors_in_house    12026 non-null  int64
 7   year_of_building   12026 non-null  int64
 8   price              12026 non-null  float64
 9   district           12026 non-null  str
 10  city               12026 non-null  str
 11  geo_region         12026 non-null  str
dtypes: float64(4), int64(4), object(1), str(3)
memory usage: 1.2+ MB

In [46]:
df_Kyiv_clean.drop(["city", "geo_region"], axis=1, inplace=True)

In [47]:
categorical_cols_kyiv = ['district', 'freshly_renovated'] 

df_kyiv_encoded = pd.get_dummies(df_Kyiv_clean, columns=categorical_cols_kyiv, drop_first=True, dtype=int)

print("Колонки київської моделі після OHE:")
print(df_kyiv_encoded.columns.tolist())

Колонки київської моделі після OHE:
['num_of_rooms', 'area', 'living_area', 'kitchen_area', 'floor', 'floors_in_house', 'year_of_building', 'price', 'district_Desnianskyi', 'district_Dniprovskyi', 'district_Holosiivskyi', 'district_Obolonskyi', 'district_Pecherskyi', 'district_Podilskyi', 'district_Shevchenkivskyi', 'district_Solomianskyi', 'district_Sviatoshynskyi', 'freshly_renovated_True']

In [48]:
categorical_cols_regions = ['city', 'district', 'freshly_renovated', 'geo_region']

df_ukraine_encoded = pd.get_dummies(df_ukraine_clean, columns=categorical_cols_regions, drop_first=True, dtype=int)


print("\nКолонки моделі регіонів після OHE:")
print(df_ukraine_encoded.columns.tolist())

Колонки моделі регіонів після OHE:
['num_of_rooms', 'area', 'living_area', 'kitchen_area', 'floor', 'floors_in_house', 'year_of_building', 'price', 'is_large_city', 'is_close_to_eu', 'is_near_border_threat', 'is_tourist_hub', 'is_low_floor', 'is_high_floor', 'is_historic_or_stalinka', 'is_khrushchev', 'is_soviet_panel', 'is_modern_fund', 'city_Chernihiv', 'city_Chernivtsi', 'city_Dnipro', 'city_Ivano-Frankivsk', 'city_Kharkiv', 'city_Kherson', 'city_Khmelnytskyi', 'city_Kropyvnytskyi', 'city_Lutsk', 'city_Lviv', 'city_Mykolaiv', 'city_Odesa', 'city_Poltava', 'city_Rivne', 'city_Sumy', 'city_Ternopil', 'city_Uzhhorod', 'city_Vinnytsia', 'city_Zaporizhzhia', 'city_Zhytomyr', 'district_Outskirts', 'district_Residential', 'freshly_renovated_True', 'geo_region_East', 'geo_region_North', 'geo_region_South', 'geo_region_West']

In [49]:
df_ukraine_encoded.to_csv("Ukraine.csv")
df_kyiv_encoded.to_csv("Kyiv_ML.csv")